site_name: NCP
description: サッカーをこよなく愛する少年少女のため、イベントの企画・制作・運営を一貫してサポートします。
event_title: 第3回ユニックカップ U-9 サッカー大会
event_date: 2026年10月10日（土）
event_place: 千葉県習志野市 芝園フットサル場
event_link: /第３回ユニックカップu-9サッカー大会開催決定/
instagram_url: https://www.instagram.com/ncptokyo.net_official/
youtube_url: https://www.youtube.com/@NCPTOKYO
contact_email: info@ncptokyo.net
